main_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('members/', views.member_detail, name='member_detail'),
  path('members/create/', views.member_create, name='members_create'),
  path('jobs/', views.jobs_index, name='index'),
  path('jobs/<int:job_id>/', views.jobs_detail, name='detail'),
  path('jobs/create/', views.jobs_create, name='jobs_create'),
  path('jobs/<int:pk>/update', views.JobUpdate.as_view(), name='jobs_update'),
  path('jobs/<int:pk>/delete', views.JobDelete.as_view(), name='jobs_delete'),
  path('jobs/<int:job_id>/add_job_photo', views.add_job_photo, name='add_job_photo'),
  path('jobs/<int:job_id>/assoc_contractor/<int:contractor_id>/', views.assoc_contractor, name='assoc_contractor'),
  path('contractors/', views.ContractorList.as_view(), name='contractors_index'),
  path('contractors/<int:contractor_id>/', views.contractors_detail, name='contractors_detail'),
  path('contractors/create/', views.ContractorCreate.as_view(), name='contractors_create'),
  path('contractors/<int:pk>/update/', views.ContractorUpdate.as_view(), name='contractors_update'),
  path('contractors/<int:pk>/delete/', views.ContractorDelete.as_view(), name='contractors_delete'),
  path('contractors/<int:contractor_id>/add_contractor_photo', views.add_contractor_photo, name='add_contractor_photo'),
  path('contractors/<int:contractor_id>/add_review/', views.add_review, name='add_review'),
  path('accounts/signup/', views.signup, name='signup'),
]

yardbarker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from phone_field import PhoneField
from django import forms


class Contractor(models.Model):
  name = models.CharField(max_length=100)
  phone = PhoneField(blank=True, help_text='Contact phone number')
  email = models.EmailField(max_length=150)
  location = models.CharField(max_length=150)
  rating = models.FloatField(default=0)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('contractors_detail', kwargs={'contractor_id': self.id})


class Member(models.Model):
  name = models.CharField(max_length=100)
  phone = PhoneField(blank=True, help_text='Contact phone number')
  email = models.EmailField(max_length=150)
  location = models.CharField(max_length=150)
  rating = models.FloatField(default=0)
  user = models.OneToOneField(User, primary_key=True, on_delete=models.CASCADE)
  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('user_detail', kwargs={'pk': self.id})


class Review(models.Model):
  RATING_CHOICES = (
    ('1', '⭐️'),
    ('2', '⭐️⭐️'),
    ('3', '⭐️⭐️⭐️'),
    ('4', '⭐️⭐️⭐️⭐️'),
    ('5', '⭐️⭐️⭐️⭐️⭐️')
  )

  date = models.DateField(auto_now_add=True)
  rating = models.CharField(max_length=1, choices=RATING_CHOICES, blank=True)
  content = models.TextField(max_length=500, blank=True)
  contractor = models.ForeignKey(Contractor, on_delete=models.CASCADE)
  member = models.ForeignKey(Member, default=None, on_delete=models.CASCADE)

  def __str__(self):
    return f'{self.contractor} - {self.rating}'

  class Meta:
    ordering = ['-date']


class Job(models.Model):
  DONE_OR_NOT = (
    ('1', 'Done'),
    ('2', 'Not Done')
  )

  name = models.CharField(max_length=100)
  task = models.CharField(max_length=150)
  location = models.CharField(max_length=100)
  reward = models.IntegerField()
  description = models.TextField(max_length=250)
  isDone = models.CharField(choices=DONE_OR_NOT, default='2', max_length=1)
  member = models.ForeignKey(Member, default=None, on_delete=models.CASCADE)
  contractors = models.ManyToManyField(Contractor)

  def __str__(self):
    return f'{self.name} ({self.id})'

  def get_absolute_url(self):
    return reverse('detail', kwargs={'job_id': self.id})


class JobPhoto(models.Model):
  url = models.CharField(max_length=200)
  job = models.ForeignKey(Job, on_delete=models.CASCADE)

  def __str__(self):
    return f"Photo for job_id: {self.job_id} @{self.url}"


class MemberPhoto(models.Model):
  url = models.CharField(max_length=200)
  member = models.ForeignKey(Member, on_delete=models.CASCADE)

  def __str__(self):
    return f"Photo for Member_id: {self.member_id} @{self.url}"


class ContractorPhoto(models.Model):
  url = models.CharField(max_length=200)
  contractor = models.ForeignKey(Contractor, on_delete=models.CASCADE)

  def __str__(self):
    return f"Photo for Contractor_id: {self.contractor_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from django import forms
from .models import Review, Job, Member


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'content']


class JobCreateForm(forms.ModelForm):
  class Meta:
    model = Job
    fields = ['name', 'task', 'location', 'reward', 'description']


class MemberCreateForm(forms.ModelForm):
  class Meta:
    model = Member
    fields = ['name', 'phone', 'email', 'location']

main_app/views.py
import os
import uuid
import boto3
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Job, Member, Review, Contractor, JobPhoto, MemberPhoto, ContractorPhoto
from .forms import ReviewForm, JobCreateForm, MemberCreateForm
from django.contrib.auth.models import User


def home(request):
  return render(request, 'home.html')


def about(request):
  return render(request, 'about.html')


@login_required
def member_detail(request):
  curr_member = Member.objects.get(user=request.user)
  job_list = Job.objects.filter(member=curr_member).order_by('-isDone')
  completed_list = job_list.filter(isDone='1')
  not_complete_list = job_list.filter(isDone='2')
  
  return render(request, 'member_detail.html', {
    'member': curr_member,
    'job_list': job_list,
    'completed_list': completed_list,
    'not_complete_list': not_complete_list,
  })


@login_required
def jobs_index(request):
  jobs = Job.objects.filter(isDone='2')
  return render(request, 'jobs/index.html', {
    'jobs': jobs
  })


@login_required
def assoc_contractor(request, job_id, contractor_id):
  Job.objects.get(id=job_id).contractors.add(contractor_id)
  return redirect('detail', job_id = job_id)


@login_required
def jobs_detail(request, job_id):
  job = Job.objects.get(id=job_id)
  id_list = job.contractors.all().values_list('id')
  contractors_available = Contractor.objects.exclude(id__in=id_list)
  return render(request, 'jobs/detail.html', {
    'job': job,
    'contractors': contractors_available
  })


class JobUpdate(LoginRequiredMixin, UpdateView):
  model = Job
  fields = ['name', 'task', 'location', 'reward', 'description', 'isDone']


class JobDelete(LoginRequiredMixin, DeleteView):
  model = Job
  success_url = '/jobs'


class ContractorList(LoginRequiredMixin, ListView):
  model = Contractor


class ContractorDetail(LoginRequiredMixin, DetailView):
  model = Contractor


class ContractorCreate(LoginRequiredMixin, CreateView):
  model = Contractor
  fields = ['name', 'phone', 'email', 'location']


class ContractorUpdate(LoginRequiredMixin, UpdateView):
  model = Contractor
  fields = ['phone', 'email', 'location']


class ContractorDelete(LoginRequiredMixin, DeleteView):
  model = Contractor
  success_url = '/contractors'


def jobs_create(request):
  member = Member.objects.get(user=request.user)
  error_message = ''
  job_create_form = JobCreateForm()
  if request.method == 'POST':
    form = JobCreateForm(request.POST)
    if form.is_valid():
      new_job = form.save(commit=False)
      new_job.isDone = '2'
      new_job.member = member
      new_job.save()
      return redirect('detail', job_id=new_job.id)
    else:
      error_message = 'You are not a member or this is an invalid form'
  return render(request, 'jobs/create.html', {
    'member': member,
    'job_create_form': job_create_form,
    'error_message': error_message
  })


def member_create(request):
  error_message = ''
  member_create_form = MemberCreateForm()
  if request.method == 'POST':
    form = MemberCreateForm(request.POST)
    if form.is_valid():
      new_member = form.save(commit=False)
      new_member.user = request.user
      new_member.save()
      return redirect('member_detail')
    else:
      error_message = 'You are not a member or this is an invalid form'
  return render(request, 'member_create.html', {
    'member_create_form': member_create_form,
    'error_message': error_message
  })


class MemberUpdate(UpdateView):
  model = Member
  fields = ['name', 'phone', 'email', 'location']


@login_required
def add_job_photo(request, job_id):
  photo_file = request.FILES.get('photo-file', None)
  if photo_file:
    s3 = boto3.client('s3')
    key = uuid.uuid4().hex[:6] + \
      photo_file.name[photo_file.name.rfind('.'):]
    try:
      bucket = os.environ['S3_BUCKET']
      s3.upload_fileobj(photo_file, bucket, key)
      url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
      JobPhoto.objects.create(url=url, job_id=job_id)
    except Exception as e:
      print('An error occurred uploading file to S3')
      print(e)
    return redirect('detail', job_id=job_id)


@login_required
def add_contractor_photo(request, contractor_id):
  photo_file = request.FILES.get('photo-file', None)
  if photo_file:
    s3 = boto3.client('s3')
    key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
    try:
      bucket = os.environ['S3_BUCKET']
      s3.upload_fileobj(photo_file, bucket, key)
      url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
      ContractorPhoto.objects.create(url=url, contractor_id=contractor_id)
    except Exception as e:
      print('An error occurred uploading file to S3')
      print(e)
    return redirect('contractors_detail', contractor_id=contractor_id)


@login_required
def add_review(request, contractor_id):
  form = ReviewForm(request.POST)
  curr_contractor = Contractor.objects.get(id=contractor_id)
  print(request.user)
  curr_member = Member.objects.get(user=request.user)
  if form.is_valid():
    new_review = form.save(commit=False)
    new_review.contractor = curr_contractor
    new_review.member = curr_member
    new_review.save()
    print(new_review)
  return redirect('contractors_detail', contractor_id=contractor_id)


def contractors_detail(request, contractor_id):
  contractor = Contractor.objects.get(id=contractor_id)
  contractor_rev = Review.objects.filter(contractor=contractor_id)
  sum = 0
  for review in contractor_rev:
    print(f"rating: {float(review.rating)}")
    sum += float(review.rating)
  if sum == 0:
    average = 0
  else:
    average = round(sum / len(contractor_rev), 1)
  form = ReviewForm()
  return render(request, 'main_app/contractor_detail.html', {
    'contractor': contractor,
    'review_form': form,
    'average': average,
  })


def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('members_create')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

main_app/templates/jobs/create.html
{% extends 'base.html' %}
{% block content %}

<div class="profile_page">
  <h1>Add Job</h1>
  <form action="{% url 'jobs_create'%}" method="POST">
    {% csrf_token %}
    <!-- Render the inputs -->
    {{ job_create_form.as_p }}
    <p class="disclaimer">*Please add photos of your job (if applicable) after hitting submit and successfully adding your job.</p>
    <input type="submit" class="btn" value="Add Job" id="job_submit">
  </form>
</div>

{% endblock %}

main_app/templates/jobs/detail.html
{% extends 'base.html' %}
{% block content %}

<div class="profile_page">
  <h1>Job Details</h1>

  <div class="container">
    <section id="job_detail">
      <div id="job_content_card" class="card">
        <div class="card-content">
          <span class="card-title">{{ job.name }}</span>
          <p><span>Task: </span>{{ job.task }}</p>
          <p><span>Location: </span>{{ job.location }}</p>
          <p><span>Reward: </span>${{ job.reward }}</p>
          <p><span>Description: </span>{{ job.description }}</p>
          <p><span>Is Done: </span>
            {% if job.isDone == '2' %}
              Not yet!
            {% else %}
              This job has been done.
            {% endif %}
          </p>
          <p><span>Poster: </span>{{ job.member }}</p>
          {% for contractor in job.contractors.all %}
            <p><span>Contractor: </span>{{ contractor }}</p>
          {% endfor %}
        </div>
        <div class="card-action">
          <a href="{% url 'jobs_update' job.id %}">Edit</a>
          <a href="{% url 'jobs_delete' job.id %}">Delete</a>
        </div>
      </div>
      <div id="map">
        <iframe
          width="500"
          height="350"
          style="border:0"
          loading="lazy"
          allowfullscreen
          referrerpolicy="no-referrer-when-downgrade"
          src="https://www.google.com/maps/embed/v1/place?key=AIzaSyAyXA5trBp5kK0p357_ocso-mNFbn6J5z0&q={{ job.location }}">
        </iframe>
      </div>  
    </section> 
  </div>

  <div class="row" id="job_photo">
    {% for photo in job.jobphoto_set.all %}
      <img class="responsive-img card-panel" src="{{photo.url}}">
    {% empty %}
      <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}
    <form action="{% url 'add_job_photo' job.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
      {% csrf_token %}
      <input type="file" name="photo-file">
      <br><br>
      <button type="submit" class="btn">Upload Photo</button>
    </form>
  </div>



  <hr>
  <div class="row">
    <div class="col s6">
      <h3>{{ job.name }}'s Contractors</h3>
      {% if job.contractors.count %}
        {% for contractor in job.contractors.all %}
          <div class="card">
            <div class="card-content">
              <h5 id="job-status">{{ contractor.name }} is currently working on {{ job.name }}</h5>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <h5>No Contractors </h5>
      {% endif %}
    </div>
  </div>

  <div class="col s6" id="available_con">
    <h3>Available Contractors</h3>
    {% if contractors.count %}
      {% for contractor in contractors.all %}
        <div class="card">
          <div class="card-content">
            <h5>{{ contractor.name }} is available to work!</h5>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_contractor' job.id contractor.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No More Available Contractors.</h5>
    {% endif %}
  </div>
</div>

{% endblock %}

main_app/templates/jobs/index.html
{% extends 'base.html' %}
{% block content %}

<div class="profile_page"> 
  <h1>Job List</h1>

  {% for job in jobs %}
    <a href="{% url 'detail' job.id %}">
      <div class="card">
        <div class="card-content">
          <span class="card-title">{{ job.name }}</span>
          <p><span>Task: </span>{{ job.task }}</p>
          <p><span>Location: </span>{{ job.location }}</p>
          <p><span>Reward: </span>${{ job.reward }}</p>
          <p><span>Description: </span>{{ job.description }}</p>
        </div>
      </div>
    </a>
  {% endfor %}
</div>

{% endblock %}